# docker-compose will be used for local-deployment only
services:
  postgres:
    image: postgres:16
    container_name: my-postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-expense}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
#
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expensetrackerapi-1.0.0.jar
    image: dockermerch/expensetrackerapi-1.0.0
    platform: linux/amd64
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-expense}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - "8080:8080"

volumes:
  pg_data:
